# Generated by Django 3.0.5 on 2020-06-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=300)),
                ('taskDescription', models.TextField()),
                ('taskTime', models.TimeField(auto_now=True)),
            ],
        ),
    ]
